Game logic and doors generation
Ane1y/rogue pull request #5
Opened 2023-06-05 22:50 UTC by Ane1y

2023-06-05 23:45 UTC, BurnBirdX7 requested changes
Мало тестов -3 балла

2023-06-05 23:45 UTC, BurnBirdX7 commented on app/src/main/java/ru/itmo/rogue/model/GameLogic.java
> +        state.levelMap = levelBuilder.build();
Можно
```java
var levelBuilder = new LevelBuilder();
state.levelMap = levelBuilder
    .complexity(complexity)
    .build();
```

2023-06-05 23:45 UTC, BurnBirdX7 commented on app/src/main/java/ru/itmo/rogue/model/GameLogic.java
> +        for (int i = 0; i < numberOfEnemies; i++) {
Определение числа врагов стоит вынести куда-то в отдельную функцию.
Ещё `state.player.getLevel()` уже равно `complexity`, можно было использовать его

2023-06-05 23:45 UTC, BurnBirdX7 commented on app/src/main/java/ru/itmo/rogue/model/state/Map.java
> +
Перепутаны ширина и высота

2023-06-05 23:45 UTC, BurnBirdX7 commented on app/src/main/java/ru/itmo/rogue/model/game/LevelBuilder.java
> +        map.setTile(generateDoor(map), Map.MapTile.DOOR_OUT_HARD);
Всегда генерируются одинаковые двери

2023-06-05 23:45 UTC, BurnBirdX7 commented on app/src/main/java/ru/itmo/rogue/model/GameLogic.java
> +        delta.setMap(state.levelMap);
Генерация карты никак не зависит от того в какую дверь мы вошли

2023-06-05 23:45 UTC, BurnBirdX7 commented on app/src/main/java/ru/itmo/rogue/model/game/LevelBuilder.java
> +    }
Обойти комнату DFS от входа - составить список клеток досягаемых из двери. Можно отслеживать расстояние при обходе, и добавлять в список только клеты на расстоянии больше чем минимальное.

Выбирать позицию для выхода как рандомно из списка.

2023-06-05 23:45 UTC, BurnBirdX7 commented on app/src/main/java/ru/itmo/rogue/model/state/Map.java
> +        var curTileType = getTile(pos);
maybe `isExit()`?

2023-06-05 23:45 UTC, BurnBirdX7 commented on app/src/main/java/ru/itmo/rogue/model/state/Map.java
> +
`QueueNode` - UpperCamelCase

2023-06-05 23:45 UTC, BurnBirdX7 commented on app/src/main/java/ru/itmo/rogue/model/state/Map.java
> +    }
`isCellInbound()`?

2023-06-05 23:45 UTC, BurnBirdX7 commented on app/src/main/java/ru/itmo/rogue/model/state/Map.java
> +        // These arrays show the 4 possible movement from a cell
`getDistance()`?

2023-06-05 23:45 UTC, BurnBirdX7 commented on app/src/main/java/ru/itmo/rogue/model/state/Map.java
> +
Перепутаны высота и ширина

2023-06-05 23:45 UTC, BurnBirdX7 commented on app/src/main/java/ru/itmo/rogue/model/state/Map.java
> +                if (isCellValid(row, col) && map[row][col] == MapTile.FLOOR && !visited[row][col]) {
Используй `getTiles(x, y)` вместо `map[row][col]`

2023-06-05 23:45 UTC, BurnBirdX7 commented on app/src/main/java/ru/itmo/rogue/model/state/Map.java
> +
Работай в терминах X, Y а не столбцов/колонок

2023-06-05 23:45 UTC, BurnBirdX7 commented on app/src/main/java/ru/itmo/rogue/model/state/Map.java
> +
Стоит хранить как 4 `Position`а,  а не два массива безотносительных значений (мб стоит завести класс `Movement`/`PositionShift` специально для хранения относительных позиций.

2023-06-05 23:45 UTC, BurnBirdX7 commented on app/src/main/java/ru/itmo/rogue/model/state/Map.java
> +                return u.dist;
Сделай у `Position` метод `equals` и используй его для сравнения двух точек

2023-06-05 23:46 UTC, Ane1y commented
> Мало тестов -3 балла

у меня тестов больше чем у всех в этом проекте...

2023-06-05 23:47 UTC, Ane1y commented on app/src/main/java/ru/itmo/rogue/model/GameLogic.java
> +        state.levelMap = levelBuilder.build();
фига

2023-06-05 23:48 UTC, Ane1y commented on app/src/main/java/ru/itmo/rogue/model/state/Map.java
> +        // These arrays show the 4 possible movement from a cell
ладно...

2023-06-05 23:48 UTC, Ane1y commented on app/src/main/java/ru/itmo/rogue/model/game/LevelBuilder.java
> +    }
бфсом!!

2023-06-05 23:49 UTC, BurnBirdX7 commented on app/src/main/java/ru/itmo/rogue/model/state/Map.java
> +
Что такое `int dist`?

2023-06-05 23:49 UTC, BurnBirdX7 commented on app/src/main/java/ru/itmo/rogue/model/state/Map.java
> +    }
Должно быть в терминах X, Y не col/row

2023-06-05 23:54 UTC, BurnBirdX7 commented on app/src/main/java/ru/itmo/rogue/model/state/Map.java
> +                if (isCellValid(row, col) && map[row][col] == MapTile.FLOOR && !visited[row][col]) {
`map[row][col] == MapTile.FLOOR` также уже должно быть в функции `isFree`

2023-06-06 12:41 UTC, BurnBirdX7 requested changes

2023-06-06 12:41 UTC, BurnBirdX7 commented on app/src/main/java/ru/itmo/rogue/model/GameLogic.java
> +        }
может
```java
complexity = switch (state.doorOut) {
    case DOOR_OUT_HARD -> (int)Math.floor(complexity * 1.5);
    case DOOR_OUT_NORMAL -> complexity;
    case DOOR_OUT_TREASURE_ROOM -> 0;
}
```

2023-06-06 12:41 UTC, BurnBirdX7 commented on app/src/main/java/ru/itmo/rogue/model/GameLogic.java
> +        var unitFactory = new UnitFactory(complexity);
Предыдущий список `state.units` не был очищен

2023-06-06 12:41 UTC, BurnBirdX7 commented on app/src/main/java/ru/itmo/rogue/model/GameLogic.java
> +        }
Этим уже должен был заняться `UnitFactory`

2023-06-06 12:41 UTC, BurnBirdX7 commented on app/src/main/java/ru/itmo/rogue/model/GameLogic.java
> +    }
Должен быть зашит в `Map` как поле, значение задано `LevelBuilder`-ом

2023-06-06 12:41 UTC, BurnBirdX7 commented on app/src/main/java/ru/itmo/rogue/model/GameLogic.java
> +        }
Зачем нужно поле `doorOut`, которое может хранить в себе любой тайл, а по умолчанию это вообще `DOOR_IN` (???).

Вместо этого можно использовать `state.map.getTile(state.player.getPosition())`,
если это длинно, в `State` можно добавить метод `getPlayerTile()`, который будет делать то же самое. (вместо нового поля с непонятной периодичностью обновления)

2023-06-06 12:41 UTC, BurnBirdX7 commented on app/src/main/java/ru/itmo/rogue/model/LevelLogic.java
> +            state.doorOut = state.levelMap.getTile(curPos);
Тут тоже `doorOut`, этого обновления можно избежать, если завести метод вместо поля

2023-06-06 12:41 UTC, BurnBirdX7 commented on app/src/main/java/ru/itmo/rogue/model/game/LevelBuilder.java
> +        map.setTile(generateDoor(map), Map.MapTile.DOOR_OUT_HARD);
Всё ещё одинаковые двери, но пока забьём

2023-06-06 12:41 UTC, BurnBirdX7 commented on app/src/main/java/ru/itmo/rogue/model/game/LevelBuilder.java
> +
Это должно быть поле класса `Map`, а не `LevelBuilder`. Оно может быть в `LevelBuilder`, но оно тут не очень полезно.

2023-06-06 12:41 UTC, BurnBirdX7 commented on app/src/main/java/ru/itmo/rogue/model/game/LevelBuilder.java
> +    }
Должен быть (ещё или вместо) статичный метод от `complexity`, который содержит в себе формулу вычисления. 
Сейчас формула у тебя зарыта где-то в коде.

2023-06-06 12:41 UTC, BurnBirdX7 commented on app/src/main/java/ru/itmo/rogue/model/game/LevelBuilder.java
> +        }
Чудовищно, но поправим потом

2023-06-06 12:41 UTC, BurnBirdX7 commented on app/src/main/java/ru/itmo/rogue/model/game/unit/Movement.java
Когда я говорил про Movement, я вообще не это имел ввиду.
Я имел ввиду класс который по структуре точно такой же абсолютно как `Position`, просто применяется там где семантически нужно смещение, а не позиция.

Можно его даже сделать как
```java
    public record Movement(int x, int y) {
        static List<Movement> defaults = Arrays.asList(
                new Movement(-1, 0),
                new Movement(0, -1),
                new Movement(0, +1),
                new Movement(+1, 0)
        );
    }
```
Хотя список значений по умолчанию тут совсем не обязателен

2023-06-06 12:41 UTC, BurnBirdX7 commented on app/src/main/java/ru/itmo/rogue/model/state/Map.java
> +        var curTileType = getTile(pos);
**maybe**

2023-06-06 12:41 UTC, BurnBirdX7 commented on app/src/main/java/ru/itmo/rogue/model/state/Map.java
> +    }
Всё ещё странное имя у метода

2023-06-06 12:41 UTC, BurnBirdX7 commented on app/src/main/java/ru/itmo/rogue/model/state/State.java
> +    public Map.MapTile doorOut = Map.MapTile.DOOR_IN;
Не люблю это поле :{

2023-06-06 18:29 UTC, merged